version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.53.4
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus_setup/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  postgres:
    image: postgres:17.4
    container_name: myops_postgres_container
    restart: always
    environment:
      POSTGRES_USER: myoperationsuser
      POSTGRES_PASSWORD: myoperationspassword
      POSTGRES_DB: myops
    ports:
      - "5432:5432"
    volumes:
      - myops_postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:9.2.0
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin_setup/servers.json:/pgadmin4/servers.json



volumes:
  myops_postgres_data:
    driver: local
  pgadmin_data:
    driver: local
