name: Deploy MkDocs to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the 'main' branch. Change this if your default branch is different.

jobs:
  build-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the latest Python 3 version

      - name: Install MkDocs and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs
          pip install mkdocs-material  # Required if you're using the Material theme
          pip install mkdocs-git-revision-date-localized-plugin  # Example for any custom plugins (optional)

      - name: Build the documentation
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}    # GitHub token provided by Actions
          publish_dir: ./site                          # The directory containing the built files
                      # The directory containing the built files